name: Release

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 12 15 * *"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true
      - name: Install dependencies
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop install 7zip nasm
      - name: Build
        run: .\build.win.ps1
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.DATESTAMP }}
          files: SM5-Build-${{ env.DATESTAMP }}-win64.zip
  build-mac:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64, arm64]
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: brew install nasm create-dmg
      - name: Build
        run: ./build.mac.sh ${{ matrix.arch }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.DATESTAMP }}
          files: SM5-Build-${{ env.DATESTAMP }}-mac-${{ matrix.arch }}.dmg
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get -qqy update && sudo apt-get -qqy install
          ffmpeg
          libasound2-dev
          libgl-dev
          libglew-dev
          libgtk-3-dev
          libjack-dev
          libjsoncpp-dev
          libmad0-dev
          libpng-dev
          libpulse-dev
          libtomcrypt-dev
          libtommath-dev
          libudev-dev
          libva-dev
          libvorbis-dev
          libxinerama-dev
          libx11-dev
          libxrandr-dev
          libxtst-dev
          ninja-build
      - name: Build
        run: ./build.linux.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.DATESTAMP }}
          files: SM5-Build-${{ env.DATESTAMP }}-linux.tar.gz
