name: Release

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 12 15 * *"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true
      - name: Install dependencies
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop install 7zip nasm
      - name: Build
        run: .\build.ps1
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.DATESTAMP }}
          files: SM5-Build-${{ env.DATESTAMP }}-win64.zip
