name: Release

on: [push, pull_request]

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Repository checkout
        uses: actions/checkout@v3
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true
      - name: Setup NSIS
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop update
          scoop bucket add extras
          scoop install nsis
      - name: Build
        run: |
          .\build.ps1
